import Register from "@/components/Register/Register";
import Head from "next/head";
import { yupResolver } from "@hookform/resolvers/yup";
import { useForm, FormProvider } from "react-hook-form";
import { schema } from "./schema/schema";

const RegisterPage = () => {
  const methods = useForm({
    resolver: yupResolver(schema),
  });

  return (
    <>
      <Head>
        <title>Registro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FormProvider {...methods}>
        <Register />
      </FormProvider>
    </>
  );
};

export default RegisterPage;
