import Register from '@/components/Register/Register'
import Head from 'next/head'
import * as yup from "yup";
import { yupResolver } from '@hookform/resolvers/yup';
import { useForm, FormProvider } from 'react-hook-form'

const RegisterPage = () => {
  const schema = yup.object().shape({
    firstname: yup.string().required('El nombre es requerido'),
    lastname: yup.string().required("El apellido es requerido"),
    email: yup.string().email('El email es inválido').required('El email es requerido'),
    dni: yup.number().required("El DNI es requerido").min(8, 'El Documento de identidad unica debe tener al menos 8 caracters').max(8, 'El Documento de identidad unica no debe tener mas de 8 caracteres'),
    password: yup.string().min(6, "La contraseña debe contener al menos 6 caracteres").max(20, "La contraseña no debe contener mas de 20 caracteres").matches(/^(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])/, "Usa entre 6 y 20 carácteres (debe contener al menos al menos 1 carácter especial, una mayúscula y un número").required("La contraseña es requerida"),
    confirmPassword: yup.string().oneOf([yup.ref('password')], 'Las contraseñas deben coincidir'),
    phone: yup.string().required("El telefono es requerido")
  });
  const methods = useForm({
    resolver: yupResolver(schema)
  });

  return (
    <>
        <Head>
            <title>Registro</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <FormProvider {...methods}>
            <Register/>
        </FormProvider>
    </>
  )
}

export default RegisterPage